string:
  pnjName:
    wood: "Bob"
    coal: "Didier"
    gold1: "Rodrigues de Pomero"
    gold2: "Andr√© de Pomero"
    iron: "Jean-Pierre Fanguin"
    diam: "Baruk, the collector"
    lapis: "Fabala, the enchanter"
  clickInventory:
    launchGame: "&2StartGame"
    red: "&4Red Team"
    blue: "&1Blue Team "
    spectator: "&7Spectateur"
    option: "&fOptions"
    return: "&fBack"
    cancelGame: "&4CancelGame"
  inventoryName:
    team: "&7Team"
    cancelStart: "&7CancelStart"
    options: "&7Options"
  sentence:
    secondLeft: "<x> seconds left !"
    needOp: "You need to be an operator to do this action."
    start: "&eStart the Game!"
    cancel: "Canceling the game"
    end: "End"
    teleport: "Teleporting player"
    avoidBreaking: "Can't break this block"
    opDoors: "Door opening"
    finalPhase: "A team has open their last door. Starting the final Phase..."
    checkStart:
      launched: "Initialize the countdown..."
      countdownStarted: "CountDown already launch."
      needPlayers: "Not enough players."
      alreadyLaunched: "Party already started !"
      cancelStart: "Launch canceled."
      noCountdown: "Any countdown aren't set right now."
      noGame: "Any game is playing right now."
      quitingReset: "Not enough player remaining, resetting the game."
    timescales:
      nearNight: "The moon appears soon, be careful of monster"
      nearDay: "The sun is rising, a little rest for you"
      night: "Night Time"
      day: "Day Time"
    debug:
      setPlayer: "&a<player>&f <be> ready to play"
      getDoors: "Resetting all doors..."
      delDoors: "Deleting all doors..."
      setVill: "Spawning all villagers..."
      killVill: "Killing all villagers..."
      giveKey: "Giving the Key !"
      notPlayer: "Player not found"
      tooManyArgument: "Too many argument."
      correctUsage: "Usage: /<command> <args>"
      cantWhilePlaying: "Can't perform this command while the game is pending."
      cantFromConsole: "Can't perform this action from the console"
  team:
    red: "Red"
    blue: "Blue"
    spec: "Spectators"
  navCompass: "&aNavigation"
  keyItem: "&9KEY"
coordinates:
  lobby:
    x: 0.5
    y: 57.0
    z: 1.5
  doorCoord:
    # default door location
    constant:
      x: 8.0
      y: 57.0
      z: -25.0
    copies:
      1:
        x: -26.0
        y: 57.0
        z: 94.0
      2:
        x: 26.0
        y: 57.0
        z: 94.0
      3:
        x: -78.0
        y: 57.0
        z: 94.0
      4:
        x: 78.0
        y: 57.0
        z: 94.0
      5:
        x: -104.0
        y: 57.0
        z: 146.0
      6:
        x: 104.0
        y: 57.0
        z: 146.0
      7:
        x: -135.0
        y: 57.0
        z: 120.0
      8:
        x: 135.0
        y: 57.0
        z: 120.0
      9:
        x: -78.0
        y: 57.0
        z: 172.0
      10:
        x: 78.0
        y: 57.0
        z: 172.0
      11:
        x: -52.0
        y: 57.0
        z: 195.0
      12:
        x: 52.0
        y: 57.0
        z: 195.0
      13:
        x: -26.0
        y: 57.0
        z: 146.0
      14:
        x: 26.0
        y: 57.0
        z: 146.0